### ISSUE TITLE
cannot GET /....

### ISSUE THREAD

**Issue by cryptix** [talenet/talenet#20]
the router currently redirects to a blank page when trying to open links _locally_ (in the app).

We should
* [ ] make a default page so that the uxer isn't stuck
* [x] tune the router for ssb content (`@...ed25519` => identity page., `%..sha256` => depending on type => idea, thread)

**Comment by baldo** [comment]
As a workaround I've disabled all markdown links that don't start with "http". This should avoid having users stuck on blank pages.

Default route: That's one thing we should add, but that won't be sufficient, as routing only applies to the part after the `#` in the URL. Therefor we will need some kind of redirection / 404 / whatever mechanism inside the electron code for maximum robustness.

`@` and `%` links: Either we find a way to prefix the links to add a proper route (including the `#`) when parsing the markdown or we need to redirect those via electron.

**Comment by baldo** [comment]
I have added some handling for ssb links. Will be published in an upcoming beta1-rc(?).

Default route and 404 / whatever handling in electron are still missing.
