### ISSUE TITLE
Errors when initializing tale:net are not shown

### ISSUE THREAD

**Issue by baldo** [talenet/talenet#7]
In #5 there is an error during tale:net initialization that only shows up in console. In that case the app is running but doesn't work properly and the user doesn't get any feedback. Therefor we should at least escalate error messages during initialization to the UI.

**Comment by cryptix** [comment]
1396d8a3a5f679f9c7b3b0d27453c7fb94a4d33c should fix this.

**Comment by cryptix** [comment]
Fixed with alpha 5.
